### ISSUE TITLE
"Hot" list sometimes isn't shown, and its absence makes the page wide

### ISSUE THREAD

**Issue by cellio** [ArtOfCode-/qpixel#49]
Through some tinkering we've done in the past, we've found sizing parameters that work most of the time, at least for me. :-)  I've occasionally noticed the page ignoring that and getting very wide.  It seems to correlate with the "hot" box not being present.

Is the "hot" box supposed to always be there?  If so, then that's probably the root cause -- the layout assumes/keys off of that somehow, assuming it will be there.  If it's not supposed to be there all the time, I'm not sure what the correct remedy is.

Here are some screenshots:

![Screen Shot 2019-12-25 at 2 40 27 PM](https://user-images.githubusercontent.com/5557942/71450013-531f7600-2727-11ea-8c90-6dac5c33f933.png)

![Screen Shot 2019-12-25 at 2 56 47 PM](https://user-images.githubusercontent.com/5557942/71450017-59aded80-2727-11ea-835f-f53d0beddbe1.png)

**Comment by ArtOfCode-** [comment]
The Hot list is deliberately not shown if there are no questions that qualify for it, because otherwise we'd just have an empty box, which looks _very_ weird. IIRC, the current criteria for Hot questions is any score > 0 in the past 24h - so if there's been no questions active in the last 24h, the Hot list won't be there. I'll have a look to see if there's a good way to make sure the layout doesn't break when that happens.

**Comment by cellio** [comment]
Ah, thanks for explaining how "hot" is decided.  I agree we don't want an empty box.

(I wasn't expecting to get a reply today; hope this low-priority ticket didn't intrude on your holiday.)
